/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Message {
  'id' : MessageId,
  'content' : string,
  'reminder' : [] | [Reminder],
  'recipient' : Principal,
  'sender' : Principal,
  'timestamp' : Time,
  'isReminder' : boolean,
}
export type MessageId = bigint;
export interface Reminder {
  'id' : ReminderId,
  'title' : string,
  'createdBy' : Principal,
  'completed' : boolean,
  'dueDate' : [] | [Time],
  'notes' : [] | [string],
}
export type ReminderId = bigint;
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReminder' : ActorMethod<
    [string, [] | [string], [] | [Time]],
    ReminderId
  >,
  'deleteMessage' : ActorMethod<[MessageId], undefined>,
  'deleteReminder' : ActorMethod<[ReminderId], undefined>,
  'getAppVersion' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessages' : ActorMethod<[Principal], Array<Message>>,
  'getReminders' : ActorMethod<[Principal], Array<Reminder>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markReminderCompleted' : ActorMethod<[ReminderId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<[Principal, string], MessageId>,
  'sendReminderAsMessage' : ActorMethod<[Principal, ReminderId], MessageId>,
  'updateReminder' : ActorMethod<
    [ReminderId, string, [] | [string], [] | [Time]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];