/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ReminderId = IDL.Nat;
export const MessageId = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'title' : IDL.Text,
  'createdBy' : IDL.Principal,
  'completed' : IDL.Bool,
  'dueDate' : IDL.Opt(Time),
  'notes' : IDL.Opt(IDL.Text),
});
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'reminder' : IDL.Opt(Reminder),
  'recipient' : IDL.Principal,
  'sender' : IDL.Principal,
  'timestamp' : Time,
  'isReminder' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReminder' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
      [ReminderId],
      [],
    ),
  'deleteMessage' : IDL.Func([MessageId], [], []),
  'deleteReminder' : IDL.Func([ReminderId], [], []),
  'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
  'getReminders' : IDL.Func([IDL.Principal], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markReminderCompleted' : IDL.Func([ReminderId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [MessageId], []),
  'sendReminderAsMessage' : IDL.Func(
      [IDL.Principal, ReminderId],
      [MessageId],
      [],
    ),
  'updateReminder' : IDL.Func(
      [ReminderId, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReminderId = IDL.Nat;
  const MessageId = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'title' : IDL.Text,
    'createdBy' : IDL.Principal,
    'completed' : IDL.Bool,
    'dueDate' : IDL.Opt(Time),
    'notes' : IDL.Opt(IDL.Text),
  });
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'reminder' : IDL.Opt(Reminder),
    'recipient' : IDL.Principal,
    'sender' : IDL.Principal,
    'timestamp' : Time,
    'isReminder' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReminder' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
        [ReminderId],
        [],
      ),
    'deleteMessage' : IDL.Func([MessageId], [], []),
    'deleteReminder' : IDL.Func([ReminderId], [], []),
    'getAppVersion' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMessages' : IDL.Func([IDL.Principal], [IDL.Vec(Message)], ['query']),
    'getReminders' : IDL.Func([IDL.Principal], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markReminderCompleted' : IDL.Func([ReminderId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [MessageId], []),
    'sendReminderAsMessage' : IDL.Func(
        [IDL.Principal, ReminderId],
        [MessageId],
        [],
      ),
    'updateReminder' : IDL.Func(
        [ReminderId, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(Time)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };